Добавить резервное копирование задач в файл. Спринт 7.
ozlik/java-kanban pull request #2
Opened 2024-10-14 06:47 UTC by ozlik

UPD 14.10
1. Добавить резервное копирование задач в файл.
2. Создать тесты для класса FileBackedTaskManager.

2024-10-15 06:17 UTC, vlolad requested changes
Привет!

В целом всё работает, но есть несколько критичных замечаний по стилю кода и оптимизации, их надо поправить. По новым тестам и сохранению/загрузке в целом ок, критичных багов не нашел

Хорошего дня!

2024-10-15 06:17 UTC, vlolad commented on src/Main.java
> +        File file1 = new File(String.valueOf(path));
Выше создается объект Path, который сразу же парсится в обычную строку. Это лишнее
Как можно поправить:
1. Убрать Path и наименование файла по-умолчанию вынести в строку-константу (лучше напрямую в класс менеджера)
2. Воспользоваться классом Files и создать файл из Path

2024-10-15 06:17 UTC, vlolad commented on src/service/InMemoryHistoryManager.java
> +    List<Task> lt = new LinkedList<>();
Название списка не отражает его назначение, плюс не нашел, где он используется. Он точно нужен?

2024-10-15 06:17 UTC, vlolad commented on src/service/FileBackedTaskManager.java
> +    public FileBackedTaskManager(File file) {
Для удобства можно ещё сделать конструктор с файлом по-умолчанию. Конструктор без параметров, файл создается в нём же

2024-10-15 06:17 UTC, vlolad commented on src/service/FileBackedTaskManager.java
> +                    InMemoryTaskManager.setIdCounter(maxId);
Молодец, что момент учла со счетчиком id в менеджере загружаемом

2024-10-15 06:17 UTC, vlolad commented on src/service/FileBackedTaskManager.java
> +    public static Task fromString(String line) {
Конвертацию в/из строки задач лучше всего вынести в отдельный класс конвертер со статическими публичными методами
Конвертация задач - не задача менеджера, плюс способ преобразования задач может изменяться (например, преобразование в json). Достаточно будет сменить конвертер, чем переписывать код класса-менеджера

2024-10-15 06:17 UTC, vlolad commented on src/service/FileBackedTaskManager.java
> +        if (type == TaskType.SUBTASK) {
Тут идеально подойдет switch-case вместо if - else if

2024-10-15 06:17 UTC, vlolad commented on src/service/FileBackedTaskManager.java
> +    public String toString(Task task) {
Метод созвучен со стандартным методом класса Object, лучше переименовать

2024-10-15 06:17 UTC, vlolad commented on src/service/FileBackedTaskManager.java
> +        switch (type) {
Лучше этот блок переписать
Дублируются в return способы формирования строки. На заранее заданных позициях id, title, status, description и вызываются одинаковыми методами. Проще будет создать StringBuilder или StringJoiner в начале метода и после добавлять в него по порядку требуемые составные части строки
Вариативные части, вроде типа задачи или списка подзадач, можно обернуть в switch-case и if блоки.

Оптимизация не стоит как требование ТЗ, так что комментарий скорее на улучшение

2024-10-15 06:17 UTC, vlolad commented on src/service/TaskManager.java
> +    Task addTask(Integer id, Task task);
Это окей, что добавлены новые методы для добавления задач с id, но в интерфейс их добавлять не надо. Плюс все подобные методы должны быть protected, чтобы доступ был только у наследников

2024-10-15 06:17 UTC, vlolad commented on src/service/FileBackedTaskManager.java
> +        return super.addTask(id, task);
Дак можно сразу super.addTask(id, task) вызывать, промежуточные методы и не нужны с:

2024-10-15 06:17 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +    protected static void setIdCounter(int id) {
static привязывает метод к классу, а не конкретным объектам. В итоге если будет несколько экземпляров менеджера, то использование setIdCounter поменяет счетчик сразу во всех
static тут надо убрать

2024-10-15 06:17 UTC, vlolad commented on src/service/FileBackedTaskManager.java
> +public class FileBackedTaskManager extends InMemoryTaskManager {
Дополнительно в класс Managers надо добавить FileBackedTaskManager. Он теперь основная реализация, так что потребуется изменить метод getDefault()

2024-10-15 06:17 UTC, vlolad commented on test/service/FileBackedTaskManagerTest.java
> +//    public void shouldLoadListOfTask() {
Если тест больше не нужен - то надо удалить закомментированные строки
Если нужен, но не сейчас - аннотация @Disabled

2024-10-16 07:53 UTC, ozlik commented on src/Main.java
> +        File file1 = new File(String.valueOf(path));
Выполнено пунктом 1.

2024-10-16 07:55 UTC, ozlik commented on src/service/InMemoryHistoryManager.java
> +    List<Task> lt = new LinkedList<>();
убрала, уже не помню, что я хотела с ним делать

2024-10-16 07:59 UTC, ozlik commented on src/service/FileBackedTaskManager.java
> +    public FileBackedTaskManager(File file) {
Добавила

2024-10-16 08:32 UTC, ozlik commented on src/service/FileBackedTaskManager.java
> +    public static Task fromString(String line) {
Готово

2024-10-16 08:32 UTC, ozlik commented on src/service/FileBackedTaskManager.java
> +    public String toString(Task task) {
Готово

2024-10-16 08:58 UTC, ozlik commented on test/service/FileBackedTaskManagerTest.java
> +//    public void shouldLoadListOfTask() {
Он не работал на самом деле, там была проблема с хисторименеджер, которая ловилась только в тестах гитхаба.  Посмотрим как в этот раз зайдет.

2024-10-16 10:55 UTC, ozlik commented on src/service/FileBackedTaskManager.java
> +        switch (type) {
сделала

2024-10-16 15:59 UTC, ozlik commented on test/service/FileBackedTaskManagerTest.java
> +//    public void shouldLoadListOfTask() {
поправили с наставником

2024-10-17 09:23 UTC, vlolad approved these changes
Привет!

Всё поправлено -> принято с:

2024-10-17 09:23 UTC, vlolad commented on src/converter/StringConverter.java
> +public class StringConverter {
Всё отлично

2024-10-17 09:23 UTC, vlolad commented on src/service/FileBackedTaskManager.java
> +        this.file = new File("testFile.csv");
Лучше такие текстовые переменные в константу выносить, но не критично для спринта

2024-10-18 05:33 UTC, merged