Добавить резервное копирование задач в файл. Спринт 8.
ozlik/java-kanban pull request #3
Opened 2024-10-27 13:07 UTC by ozlik

UPD 27.10
1. Добавить учет времени в задачи (время начала, завершения, длительность).
2. Создать метод учета времени у Эпиков в классе InMemoryTaskManager.
3. Добавить валидацию времени задач на пересечение по логике: Предполагается, что пользователь будет выполнять не более одной задачи за раз.

2024-10-28 20:03 UTC, vlolad requested changes
Привет!

В целом ок, нужны доработки для проверки пересечений и несколько комментариев по-мелочи. В остальном хорошо, за использование стримов дополнительный плюс)

Хорошего вечера!

2024-10-28 20:03 UTC, vlolad commented on src/Main.java
> +//      в чем может быть проблема?
Ну, тут надо в дебаггере посидеть, отличный тренинг)

2024-10-28 20:03 UTC, vlolad commented on src/converter/StringConverter.java
>          stringBuilder.append(type).append(",");
Всё ещё рекомендую заменить на StringJoiner, в нем можно сразу указать разделитель и убрать повторяющийся вызов `.append(",")`

2024-10-28 20:03 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +    private final Set<Task> prioritizedTasks = new TreeSet<>(
Всё отлично, правильно выбрана структура данных

2024-10-28 20:03 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +                    .map(subtasks::get)
Плюс

2024-10-28 20:03 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +                    .collect(Collectors.toCollection(ArrayList::new)); // собираем результат в ArrayList
А можно просто toList использовать, если потом этот список не изменяется

2024-10-28 20:03 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +        if (isTaskOverlap) {
Можно сразу `if (isTaskOverlap(task)) {`
А ещё лучше - убрать публичный метод и выбрасывание ошибки перенести в приватный. Публичный доступ к проверке пересечений не требуется

2024-10-28 20:03 UTC, vlolad commented on src/service/InMemoryTaskManager.java
> +    private boolean isTaskOverlap(Task task) {
Метод очень сложно скомпанован, 3 вложенных if, надо разделить

1. Если `task.getStartTime() == null` - можно сразу возвращать false
2. В цикле если `taskToCompare.getStartTime() == null` - можно сразу пропускать эту итерацию с помощью ключевого слова
3. По самой проверке:

Сравнение вместо equals надо использовать метод isEqual, он как раз для LocalDateTime.
Также сами проверки не охватывают случаи, когда новая задача начинается/заканчивается в период действия другой задачи.
Достаточно проверить два кейса:
а) Проверяем, что первый интервал начинается позже или в то же время, что и второй, и заканчивается позже начала второго интервала.
б) Или проверяем, что второй интервал начинается позже или в то же время, что и первый, и заканчивается позже начала первого интервала.

2024-10-29 05:14 UTC, ozlik commented on src/service/InMemoryTaskManager.java
> +    private boolean isTaskOverlap(Task task) {
Полностью изменила логику метода по дополнительному заданию добавив сетку расписаний.

2024-10-30 05:32 UTC, ozlik commented on src/Main.java
> +//      в чем может быть проблема?
а здесь нет ошибки, программа наоборот работает правильно, при изменении порядка задач их id меняется, поэтому не создаются сабтаски на несуществующий эпик. Я добавила вывод об ошибке вместо нуля, но не знаю насколько это будет соответствовать ТЗ.

2024-10-30 14:24 UTC, vlolad commented on src/Main.java
> +//      в чем может быть проблема?
При изменении порядка задач id не должны меняться, так что это ошибка. Но я не нашел, когда сам проект запускал. Это при загрузке из файла происходит?

2024-10-30 14:26 UTC, vlolad approved these changes
Привет!

Всё работает, принято. Не нашел кейс, когда id у задач меняются, но вообще его и не должно быть. Может я не так понял комментарий..

Хорошего вечера!

2024-10-30 14:26 UTC, vlolad commented on src/service/TaskScheduler.java
> +public class TaskScheduler {
Неплохое решение!

2024-10-31 06:37 UTC, ozlik commented on src/Main.java
> +//      в чем может быть проблема?
Нет, у меня сейчас id задается при создании задачи, т.е. создаем - присваивается id, поэтому если создание задач поменять местами, то будут разные id. Вроде бы это логично.

2024-10-31 11:35 UTC, merged