Добавлен Http Server. Спринт 9.
ozlik/java-kanban pull request #4
Opened 2024-11-12 06:00 UTC by ozlik

UPD 12.11
1. Создать класс HttpTaskServer
2. Описать логику обработки запросов в классах BaseHttpHandler и TaskHttpHandler

2024-11-12 16:43 UTC, vlolad requested changes
Привет!

Если коротко, то всё работает верно, но надо отрефакторить и разбить хендлер на несколько классов. Сейчас по сути для разных эндпоинтов создается один и тот же хендлер, который второй раз обрабатывает запрос и решает, как его обрабатывать

В остальном ок, осталось поправить эти комменты и добавить тесты, будет ок)

Хорошего вечера!

2024-11-12 16:43 UTC, vlolad commented on test/http/TaskHttpHandlerTest.java
> +
Ladno

Можно тогда убрать пустой класс, но тесты всё равно нужны для http клиента

2024-11-12 16:43 UTC, vlolad commented on src/HttpTaskServer.java
> +        httpServer.createContext("/prioritized", new TaskHttpHandler(taskManager, gson));
Для разных эндпоинтов лучше сделать разные хендлеры. Сейчас TaskHttpHandler по второму разу обрабатывает приходящий эндпоинт, хотя тут в контексте сразу известно, придет ли запрос на /tasks, /epics и т.д.

2024-11-12 16:43 UTC, vlolad commented on src/service/Managers.java
> +    public static Gson getGson() {
Можно тут, но вообще можно и в HttpTaskServer, т.к. больше нигде не используется

2024-11-12 16:43 UTC, vlolad commented on src/http/TaskHttpHandler.java
> +public class TaskHttpHandler extends BaseHttpHandler implements HttpHandler {
Всё в одной куче, надо разделить хендлеры по моделям: отдельный хендлер для запросов по /tasks, отдельный для /epics и далее по ТЗ

бОльшая часть кода по определению, каким методом запрос обрабатывать, уберётся, т.к. это изначально должен обрабатывать контекст на уровне HttpTaskServer. Т.е. ручное определение эндпоинта не требуется

2024-11-13 05:54 UTC, ozlik commented on src/service/Managers.java
> +    public static Gson getGson() {
Используется в хэнделере еще, поэтому оставила где ест ь , так как если в хэндле базовый выносить, то получается потом для тестов и для сервера будет не удобно вызывать.

2024-11-13 07:32 UTC, ozlik commented on src/http/TaskHttpHandler.java
> +public class TaskHttpHandler extends BaseHttpHandler implements HttpHandler {
Вроде сделала, то, не то?

2024-11-13 07:32 UTC, ozlik commented on test/http/TaskHttpHandlerTest.java
> +
Тесты дописала.

2024-11-14 07:29 UTC, vlolad approved these changes
Привет!

Всё отлично, принято
Поздравляю с завершением первой большой работы! Дальше будет проще и интереснее, потому что рутинные задачи с запросами возьмёт на себя фреймворк. Но руками попробовать создать клиент/сервер надо было, и получилось это довольно успешно)

Хорошего дня!

2024-11-14 07:29 UTC, vlolad commented on src/http/TaskHttpHandler.java
> +public class TaskHttpHandler extends BaseHttpHandler implements HttpHandler {
Теперь то)

2024-11-15 06:55 UTC, merged